name: primeira-pipeline
on:
  push:
    branches: ["main"]
  workflow_dispatch: 
jobs:
  primeiro-job:
    name: "Meu primeiro Job"
    runs-on: ubuntu-latest
    steps:
      - name: "Minha primeira ação"
        run: echo "Hello World!!!!"
      - name: "Segunda Ação"
        run: |
          echo "Segunda ação"
          
  segundo-job:
    name: "Instalação do ambiente NodeJS"
    runs-on: ubuntu-latest
    needs: [primeiro-job]
    steps:
      - name: "Verificação da versão do NodeJS atual"
        run: node --version
      - name: "Definição da versão 22.14.0 do NodeJS"
        uses: actions/setup-node@v4
        with:
          node-version: '22.14.0'
      - name: "Verificação da versão do NodeJS atual depois de instalar a action"
        run: node --version    
        
